apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b7eai30nw-python
  janus-idp.io/tekton: b7eai30nw-python
  backstage.io/kubernetes-id: b7eai30nw-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b7eai30nw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
